name=Cho-Z Spriggan
part=layerDual
rotationDirection=1
attack=5
defense=3
weight=5
burst=2
firstAbilityName=
secondAbilityName=
resonanceColor=1,0.15,0.15
secondResonanceColor=0.188,0.166,0.076
thirdResonanceColor=0.988,0.866,0.176
type=balance