name=Drain Fafnir
part=layer
rotationDirection=-1
attack=0
defense=2
weight=1
burst=1
firstAbilityName=Absorb
secondAbilityName=
resonanceColor=0.921,0.8,0.203
secondResonanceColor=0.921,0.8,0.203
thirdResonanceColor=0.988,0.090,0.090
type=stamina