name=Kaiser Kerbeus
part=layer
rotationDirection=1
attack=0
defense=4
weight=1
burst=2
firstAbilityName=
secondAbilityName=
resonanceColor=0,0.5,0.181
secondResonanceColor=0,1,0
thirdResonanceColor=0.8,0.8,0.8
type=defense