name=Legend Spriggan
part=layerDual
rotationDirection=1
attack=3
defense=2
weight=4
burst=1
firstAbilityName=
secondAbilityName=
resonanceColor=1,0.15,0.15
secondResonanceColor=0.188,0.166,0.076
thirdResonanceColor=1,0.3,0.3
type=balance