name=Rising Ragnaruk
part=layer
rotationDirection=1
attack=1
defense=0
weight=3
burst=2
firstAbilityName=
secondAbilityName=
resonanceColor=1,0.4,0.015
secondResonanceColor=0.988,0.606,0.176
thirdResonanceColor=.966,0.157,0.015
type=stamina