name=Sieg Xcalibur
part=layer
rotationDirection=1
attack=5
defense=0
weight=4
burst=4
firstAbilityName=
secondAbilityName=
resonanceColor=1.0,0.0,0.0
secondResonanceColor=0.988,0.866,0.176
thirdResonanceColor=0.176,0.25,1
type=attack