name=Tornado Wyvern
part=layer
rotationDirection=1
attack=0
defense=5
weight=3
burst=1
firstAbilityName=
secondAbilityName=
resonanceColor=0.91,0.074,0.918
secondResonanceColor=0.701,0.305,0.701
thirdResonanceColor=0,0.574,0.205
type=defense