name=Xeno Xcalibur
part=layer
rotationDirection=1
attack=5
defense=0
weight=0
burst=5
firstAbilityName=
secondAbilityName=
resonanceColor=1,0.15,0.15
secondResonanceColor=0.988,0.866,0.176
thirdResonanceColor=1,0.3,0.3
type=attack